using System.IO;

namespace ShmViewer.Core.Parser;

public static class CombinedHeaderBuilder
{
    public static string Build(IEnumerable<string> headerFilePaths)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// Combined header generated by SHM_VIEWER");
        sb.AppendLine("#ifndef COMBINED_HEADER_H");
        sb.AppendLine("#define COMBINED_HEADER_H");
        sb.AppendLine();
        sb.AppendLine("// Common Windows type stubs");
        sb.AppendLine("typedef unsigned char  BYTE;");
        sb.AppendLine("typedef unsigned short WORD;");
        sb.AppendLine("typedef unsigned int   UINT;");
        sb.AppendLine("typedef unsigned long  DWORD;");
        sb.AppendLine("typedef int            BOOL;");
        sb.AppendLine("typedef char           CHAR;");
        sb.AppendLine("typedef short          SHORT;");
        sb.AppendLine("typedef long           LONG;");
        sb.AppendLine("typedef unsigned long long UINT64;");
        sb.AppendLine("typedef long long          INT64;");
        sb.AppendLine();

        foreach (var path in headerFilePaths)
        {
            if (!File.Exists(path)) continue;
            sb.AppendLine($"// === {Path.GetFileName(path)} ===");
            sb.AppendLine(File.ReadAllText(path));
            sb.AppendLine();
        }

        sb.AppendLine("#endif // COMBINED_HEADER_H");
        return sb.ToString();
    }
}
