using System.IO;
using System.Text;
using System.Text.RegularExpressions;

namespace ShmViewer.Core.Parser;

/// <summary>
/// 여러 헤더 파일을 하나의 가상 헤더로 합칩니다.
/// struct/union/enum 정의를 의존성 순서(topological sort)로 재배치하여
/// Clang이 미선언 타입을 만나 int로 error recovery하는 문제를 방지합니다.
/// </summary>
public static class CombinedHeaderBuilder
{
    public static string Build(IEnumerable<string> headerFilePaths)
    {
        var paths = headerFilePaths.ToList();
        var sb = new StringBuilder();

        sb.AppendLine("// Combined header generated by SHM_VIEWER");
        sb.AppendLine("#ifndef COMBINED_HEADER_H");
        sb.AppendLine("#define COMBINED_HEADER_H");
        sb.AppendLine();
        sb.AppendLine("// Common Windows type stubs");
        sb.AppendLine("typedef unsigned char  BYTE;");
        sb.AppendLine("typedef unsigned short WORD;");
        sb.AppendLine("typedef unsigned int   UINT;");
        sb.AppendLine("typedef unsigned long  DWORD;");
        sb.AppendLine("typedef int            BOOL;");
        sb.AppendLine("typedef char           CHAR;");
        sb.AppendLine("typedef short          SHORT;");
        sb.AppendLine("typedef long           LONG;");
        sb.AppendLine("typedef unsigned long long UINT64;");
        sb.AppendLine("typedef long long          INT64;");
        sb.AppendLine();

        var raw = new StringBuilder();
        foreach (var path in paths)
        {
            if (!File.Exists(path)) continue;
            raw.AppendLine($"// === {Path.GetFileName(path)} ===");
            raw.AppendLine(File.ReadAllText(path));
            raw.AppendLine();
        }

        sb.Append(TopologicallySortStructs(raw.ToString()));
        sb.AppendLine();
        sb.AppendLine("#endif // COMBINED_HEADER_H");
        return sb.ToString();
    }

    // ──────────────────────────────────────────────────────────────
    // 내부 자료구조
    // ──────────────────────────────────────────────────────────────

    private sealed class StructBlock
    {
        public string PrimaryName { get; init; } = "";  // alias 또는 tag name
        public string TagName     { get; init; } = "";  // struct/union/enum 뒤의 이름
        public string Text        { get; init; } = "";  // 원본 소스 텍스트 (출력용)
        public string Body        { get; init; } = "";  // 중괄호 내부 텍스트, 코멘트 제거됨 (의존성 분석용)
        public readonly HashSet<string> Deps = new(StringComparer.Ordinal);
    }

    // ──────────────────────────────────────────────────────────────
    // 진입점: 전체 content에서 struct 정의를 추출하고 재배치
    // ──────────────────────────────────────────────────────────────

    private static string TopologicallySortStructs(string content)
    {
        // 코멘트를 공백으로 치환 (위치 유지) → 파싱/의존성 분석에 사용
        var stripped = StripComments(content);

        // 모든 user-defined 타입 이름 수집
        var allNames = CollectAllTypeNames(stripped);

        // 최상위 struct/union/enum 정의 블록 추출
        var blocks = new List<StructBlock>();
        var nonBlock = ExtractTopLevelBlocks(content, stripped, blocks);

        if (blocks.Count == 0)
            return content; // 정렬할 것 없음

        // 의존성 그래프 구축
        foreach (var block in blocks)
        {
            foreach (var other in blocks)
            {
                if (ReferenceEquals(block, other)) continue;
                if (ReferencesBlock(block.Body, other))
                    block.Deps.Add(other.PrimaryName);
            }
        }

        // Topological sort (Kahn's algorithm)
        var sorted = TopoSort(blocks);

        // 재조합: 비-정의 콘텐츠 먼저, 그 다음 정렬된 블록
        var sb = new StringBuilder();
        sb.AppendLine(nonBlock.TrimEnd());
        sb.AppendLine();
        foreach (var b in sorted)
        {
            sb.AppendLine(b.Text.TrimEnd());
            sb.AppendLine();
        }
        return sb.ToString();
    }

    // ──────────────────────────────────────────────────────────────
    // 타입 이름 수집
    // ──────────────────────────────────────────────────────────────

    private static HashSet<string> CollectAllTypeNames(string stripped)
    {
        var names = new HashSet<string>(StringComparer.Ordinal);

        // struct/union/enum Name { 패턴
        foreach (Match m in Regex.Matches(stripped, @"\b(?:struct|union|enum)\s+(\w+)\s*\{"))
            names.Add(m.Groups[1].Value);

        // typedef ... } Alias; 패턴 (alias 이름)
        foreach (Match m in Regex.Matches(stripped, @"\}\s*(\w+)\s*;"))
            names.Add(m.Groups[1].Value);

        return names;
    }

    // ──────────────────────────────────────────────────────────────
    // 코멘트 제거 (위치 보존: 동일 길이 공백으로 치환)
    // ──────────────────────────────────────────────────────────────

    private static string StripComments(string s)
    {
        var arr = s.ToCharArray();
        int i = 0, n = arr.Length;
        while (i < n)
        {
            if (i + 1 < n && arr[i] == '/' && arr[i + 1] == '/')
            {
                // 라인 코멘트: '\n' 전까지 공백으로
                i += 2;
                while (i < n && arr[i] != '\n') { arr[i] = ' '; i++; }
            }
            else if (i + 1 < n && arr[i] == '/' && arr[i + 1] == '*')
            {
                // 블록 코멘트: */ 까지 공백으로 (개행 문자는 유지)
                arr[i] = ' '; arr[i + 1] = ' '; i += 2;
                while (i + 1 < n && !(arr[i] == '*' && arr[i + 1] == '/'))
                {
                    if (arr[i] != '\n' && arr[i] != '\r') arr[i] = ' ';
                    i++;
                }
                if (i + 1 < n) { arr[i] = ' '; arr[i + 1] = ' '; i += 2; }
            }
            else
            {
                i++;
            }
        }
        return new string(arr);
    }

    // ──────────────────────────────────────────────────────────────
    // 최상위 정의 블록 추출
    // 반환값: 비-정의 콘텐츠 (남은 텍스트)
    // ──────────────────────────────────────────────────────────────

    private static string ExtractTopLevelBlocks(
        string content, string stripped, List<StructBlock> blocks)
    {
        var remaining = new StringBuilder();
        int i = 0, n = content.Length;

        while (i < n)
        {
            var (block, len) = TryParseBlock(content, stripped, i, n);
            if (block != null)
            {
                blocks.Add(block);
                i += len;
            }
            else
            {
                remaining.Append(content[i]);
                i++;
            }
        }
        return remaining.ToString();
    }

    // ──────────────────────────────────────────────────────────────
    // 위치 i에서 struct/union/enum 정의 블록 파싱 시도
    // ──────────────────────────────────────────────────────────────

    private static (StructBlock? block, int len) TryParseBlock(
        string content, string stripped, int start, int n)
    {
        int i = start;

        // 빠른 필터: 첫 글자가 't','s','u','e' 중 하나여야 정의 시작 가능
        char c0 = stripped[i];
        if (c0 != 't' && c0 != 's' && c0 != 'u' && c0 != 'e')
            return (null, 0);

        // 단어 경계 확인: 앞 글자가 식별자 문자면 단어 중간 → 스킵
        if (i > 0 && IsIdChar(stripped[i - 1]))
            return (null, 0);

        // ── optional 'typedef' ──
        bool hasTypedef = MatchWord(stripped, i, n, "typedef");
        if (hasTypedef)
        {
            i += 7;
            SkipWs(stripped, ref i, n);
        }

        // ── struct / union / enum 키워드 ──
        string? kw = null;
        foreach (var k in new[] { "struct", "union", "enum" })
        {
            if (MatchWord(stripped, i, n, k)) { kw = k; i += k.Length; break; }
        }
        if (kw == null) return (null, 0);

        SkipWs(stripped, ref i, n);

        // ── 선택적 tag name ──
        string tagName = "";
        if (i < n && IsIdStart(stripped[i]))
        {
            int ns = i;
            while (i < n && IsIdChar(stripped[i])) i++;
            tagName = stripped[ns..i];
        }

        SkipWs(stripped, ref i, n);

        // ── 여는 중괄호 필수 (없으면 전방 선언 or typedef 별칭 → 정의 아님) ──
        if (i >= n || stripped[i] != '{')
            return (null, 0);

        int bodyStart = i + 1;

        // ── 중괄호 카운팅으로 본문 끝 탐색 ──
        int depth = 1;
        i++;
        while (i < n && depth > 0)
        {
            if (stripped[i] == '{') depth++;
            else if (stripped[i] == '}') depth--;
            i++;
        }
        int bodyEnd = i - 1; // 닫는 '}' 위치

        SkipWs(stripped, ref i, n);

        // ── typedef alias 이름 (선택적) ──
        string alias = "";
        if (hasTypedef && i < n && IsIdStart(stripped[i]))
        {
            int ns = i;
            while (i < n && IsIdChar(stripped[i])) i++;
            alias = stripped[ns..i];
            SkipWs(stripped, ref i, n);
        }

        // ── 세미콜론 필수 ──
        if (i >= n || stripped[i] != ';')
            return (null, 0);
        i++;

        // ── 블록 구성 ──
        string primaryName = !string.IsNullOrEmpty(alias) ? alias
                           : !string.IsNullOrEmpty(tagName) ? tagName
                           : $"__anon_{start}";

        // Body는 코멘트 제거본(stripped)을 사용 → 의존성 분석 정확도 향상
        string body = stripped[bodyStart..bodyEnd];
        string text = content[start..i]; // 원본 텍스트 (코멘트 포함)

        var block = new StructBlock
        {
            PrimaryName = primaryName,
            TagName     = tagName,
            Text        = text,
            Body        = body
        };

        return (block, i - start);
    }

    // ──────────────────────────────────────────────────────────────
    // 의존성 확인: block.Body가 other의 타입 이름을 참조하는지
    // ──────────────────────────────────────────────────────────────

    private static bool ReferencesBlock(string body, StructBlock other)
    {
        if (!string.IsNullOrEmpty(other.PrimaryName) &&
            ContainsWord(body, other.PrimaryName))
            return true;

        if (!string.IsNullOrEmpty(other.TagName) &&
            other.TagName != other.PrimaryName &&
            ContainsWord(body, other.TagName))
            return true;

        return false;
    }

    private static bool ContainsWord(string text, string word)
        => Regex.IsMatch(text, $@"\b{Regex.Escape(word)}\b");

    // ──────────────────────────────────────────────────────────────
    // Topological Sort (Kahn's algorithm)
    // ──────────────────────────────────────────────────────────────

    private static List<StructBlock> TopoSort(List<StructBlock> blocks)
    {
        // name → block 매핑 (tag name 포함)
        var byName = new Dictionary<string, StructBlock>(StringComparer.Ordinal);
        foreach (var b in blocks)
        {
            byName[b.PrimaryName] = b;
            if (!string.IsNullOrEmpty(b.TagName) && b.TagName != b.PrimaryName)
                byName.TryAdd(b.TagName, b);
        }

        // in-degree 및 인접 리스트 초기화
        var inDegree = blocks.ToDictionary(b => b.PrimaryName, _ => 0);
        var adj      = blocks.ToDictionary(b => b.PrimaryName, _ => new List<string>());

        foreach (var block in blocks)
        {
            foreach (var dep in block.Deps)
            {
                // dep가 알려진 블록이어야 함
                if (!byName.TryGetValue(dep, out var depBlock)) continue;
                string depPrimary = depBlock.PrimaryName;
                if (!inDegree.ContainsKey(depPrimary)) continue;

                adj[depPrimary].Add(block.PrimaryName);
                inDegree[block.PrimaryName]++;
            }
        }

        // in-degree 0인 블록부터 큐에 삽입 (원본 순서 유지를 위해 안정 정렬)
        var queue = new Queue<string>(
            blocks.Where(b => inDegree[b.PrimaryName] == 0)
                  .Select(b => b.PrimaryName));

        var result  = new List<StructBlock>();
        var visited = new HashSet<string>(StringComparer.Ordinal);

        while (queue.Count > 0)
        {
            var name = queue.Dequeue();
            if (!visited.Add(name)) continue;
            if (byName.TryGetValue(name, out var b) && b.PrimaryName == name)
                result.Add(b);

            foreach (var dependent in adj[name])
                if (--inDegree[dependent] == 0)
                    queue.Enqueue(dependent);
        }

        // 순환 의존성 등으로 누락된 블록 후미에 추가
        foreach (var b in blocks)
            if (!visited.Contains(b.PrimaryName))
                result.Add(b);

        return result;
    }

    // ──────────────────────────────────────────────────────────────
    // 헬퍼
    // ──────────────────────────────────────────────────────────────

    private static void SkipWs(string s, ref int i, int n)
    {
        while (i < n && s[i] is ' ' or '\t' or '\n' or '\r') i++;
    }

    private static bool MatchWord(string s, int i, int n, string word)
        => i + word.Length <= n
        && s.AsSpan(i, word.Length).Equals(word, StringComparison.Ordinal)
        && (i + word.Length >= n || !IsIdChar(s[i + word.Length]));

    private static bool IsIdStart(char c) => char.IsLetter(c) || c == '_';
    private static bool IsIdChar(char c)  => char.IsLetterOrDigit(c) || c == '_';
}
